### ISSUE TITLE
Non-rectangular image via PNG Transparency

### ISSUE THREAD

**Issue by oori** [snorpey/triangulate-image#24]
Processing a transparent PNG, one would expect the transparent areas ignored,   but they are not.
Could you please point me to how/where I could handle this, in your code.

See this example, this coloured circle (with transparent background):

![image](https://cloud.githubusercontent.com/assets/200688/16638587/c4f4c13e-43e8-11e6-9dd8-f5d45bcc62d0.png)

Produces this (_superb!_) polygons with the transparent background polygonized as well..    it's beautiful, but we need it without :)
![Processed](https://cloud.githubusercontent.com/assets/200688/16638581/b7f5f926-43e8-11e6-8650-c16ba6cf7d28.png)

Thanks in advance!

**Comment by snorpey** [comment]
hey @oori,

thank you for reporting this issue! :thumbsup: unfortunately, it is currently not possible to ignore transparent areas. :confused:

however, i think you are right, the library should provide a way to do this. i think this is a feature that should be included in the next version of the library.

in the mean time, if you want to poke around in the source code a little bit yourself, you could start here: https://github.com/snorpey/triangulate-image/blob/master/src/polygons/addColorToPolygons.js
this is the place where color information is added to the polyons. maybe you'll be able to add second function that filters out all transparent polygons here.

btw: if you get it to work properly, pull requests are always welcome! :grin:

thanks again for reporting this issue!

**Comment by oori** [comment]
Thanks for the reply.
Ok,   here's the output of a quick hack:

![image](https://cloud.githubusercontent.com/assets/200688/16685176/9cd1a8bc-4509-11e6-9ed6-98d54656def4.png)

Although it looks "correct,  I guess it's **not** valid a hack,  as I just filter out polygons that are black. (color = 0,0,0).     I guess such filtering should happen earlier,  when we can still distinct _transparent_ from _black_.     where would that be?

**Comment by snorpey** [comment]
hey @oori, nice to see that you were able to make some progress!

to filter out transparent polygons, you'll probably want to modify the [_getColorByPos_](https://github.com/snorpey/triangulate-image/blob/master/src/util/getColorByPos.js) function to return an alpha value. you can probably do that by adding another line in the returned object, something like this:

```
a: colorData.data[index + 3] / 255
```

once the alpha value has been added to the color data, it should be possible to filter out transparent polygons.

please note that i'm on my phone right now, so i can't really test any of this & there might be some typos... definitely let me know if this works or you run into problems.

have a great weekend!

**Comment by oori** [comment]
Thanks!
Yes,  your suggestions work.   I am playing around with the combinations (fill,stroke,transparent-color...), and will send a PR tomorrow.     I guess I will add a new param: "transparent" that would have the same logic as the stroke/fill (_ie. string hex, or boolean false_).

Cheers.

**Comment by oori** [comment]
@snorpey Adding the `transparent` param is simple, using your alpha tip and a simple filtering function.     But,  where it gets a bit complex is how this works with the **gradient** feature.
Out-of-the-box, transparent is considered black, and the edges would all have gradient from `color --> black`.     Ideally - you'd want `color --> transparent` (_impossible?_),   or `color --> other-specific-color` (_e.g. manually specified background color_).

The solution I see is to have a `transparent` param with same logic as stroke/fill (_ie. string hex, or boolean false_).   When one wants an exact gradient, you'd set `gradient: true, transparent: '#abcdef'`   (**#abcdef as background color**),  and that generates the correct gradients. for example, see number 5 vs 6:
![image triangulation transparency example](https://cloud.githubusercontent.com/assets/200688/16764890/39b41262-4831-11e6-90f8-1da7d8dc1189.png)
_btw,  as a by-product, this does allow cool stuff like number 4._

So,  if the code is working,  why this long message and no PR ?  because:
Having the gradient solution requires a "hacky" approach - specifically, have the `getColorByPos` return the overriding transparent color, if set.  and we need to do some funky "toRGB" calculations.    I think you should validate this before I send a PR.

I will split these into separate commits on a dev branch, so you could either decide to take the full PR,  or cherry-pick just the basic `transparent:false`.

**Comment by oori** [comment]
Ok,  I've got a solution that seems stable and feature-rich enough to publish.
Just checkout from https://github.com/oori/triangulate-image/commits/transparent-gradient , `npm run build` and open the `examples/triangulate-transparent.html`

I've split it to two branches,  the complete solution: https://github.com/oori/triangulate-image/commits/transparent-gradient        but, in case you only want to pull the "_no gradients support_" solution, use this branch:  https://github.com/oori/triangulate-image/commits/transparent   (_or cherry pick_)

I didn't send a PR yet because,  I await your confirmation for the proposed solution,  after which I'll add the missing documentation, and release builds. Better get everything in one PR.

Thanks.

**Comment by oori** [comment]
a couple of tricks using transparency:   

![image triangulation transparency example](https://cloud.githubusercontent.com/assets/200688/16788466/b48ebcfc-48a5-11e6-8845-c1276c3a6572.png)

**Comment by snorpey** [comment]
hey @oori thank you so much for putting in all the time and effort to make this lib better! sorry for taking some time to reply, i just got back from vacation.

i checked out your branches and had a look, the changes all look good. however, there is one thing i noticed, that we should think about a little bit:

can we find a better name for the parameter than `transparent`? maybe something like `replaceTransparentPixels`,`transparentPixels`, `transparentAreas` or something else that describes a little bit better what the parameter actually does?

other than that, i think your code looks great, thanks again for taking the time to contribute!

**Comment by oori** [comment]
Cheers.    if the only concern with this patch is the param naming, we're cool..    So, in the context of the _complete solution_,  the `transparent` param means: `transparentColor`  Set the transparent pixel's color.  
can be a String **css name**,  `red, hsl(..), FFF, ...`    This is later converted to a rgba color object via canvas see `toColor()`  in https://github.com/oori/triangulate-image/commit/286f4dadebd1127f5261aeadf5adc37dbdd58918#diff-a1e88266f5068211ca3b06fa3858aa80R87  
can be Boolean **false**,  means: "_do _not_ paint transparent pixels_". that's the logical default state.  
Boolean **true** is invalid (_paint transparent pixels.  ok, but which color?_), so, although it actually works with true (it's black), I suspect some browser would fail, as this isn't a valid css color. so, we auto-fix it to "false".  (can change in the future,  see: https://github.com/oori/triangulate-image/commit/286f4dadebd1127f5261aeadf5adc37dbdd58918#diff-a1e88266f5068211ca3b06fa3858aa80R83) 

This param's default state is **false_:  don't paint transparent pixels.  _,  so it's more about "__please color this __" than "__show** pixel".     to the end-user, it feels pretty much like fill and stroke params,  but they aren't called fillColor, and strokeColor..     although they aren't 100% compatible (they **can** have boolean  "true", unlike transparent), it kinda makes sense to name it `transparent"`, but  I'd opt for `transparentColor`.    As project owner, I entrust you with the artistic task to choose the desired param name.   I'll do the missing docs and PR it over next week.

btw:  a by-product of adding the alpha channel to the color object, and replacing all the manual concats with`toRGBA()` function, is that you can pass transparent values to the `fill` and `stroke` as well !      This allow funky things like number-7 and number-3 in the reference example (image above)

All the best.

**Comment by snorpey** [comment]
hey @oori thanks again for your time + effort!

let's go with `transparentColor`.

i'm very much looking forward to your pull request!

**Comment by snorpey** [comment]
hey @oori i was just wondering if you need any help with the pull request? anything i can do to make things easier for you?

**Comment by oori** [comment]
@snorpey Sorry for the long delay, I am real busy these days..    I'll arrange the PR and push it soon..

**Comment by oori** [comment]
Done, checkout the commits.  
You just need to pull and bump the version up, I didn't know if you prefer 0.3.2 or a fancy 0.4.0 bump :)

**Comment by snorpey** [comment]
hey @oori i just wanted to let you know that i merged your pull request.
thank you so much for putting in all the time and effort to make this little library better! 👍

**Comment by oori** [comment]
Cheers.   it's a cool library, it was fun to add this transparency feature to it.
