### ISSUE TITLE
Question about source code

### ISSUE THREAD

**Issue by barto3** [snorpey/triangulate-image#28]
Hey, 

I am very impressed with this project, but I have some trouble understanding your code. Where is the max number of points definded?

**Comment by snorpey** [comment]
hey @barto3 thank you for your interest in this project!

in the source code, the max number of points is called `vertexCount`. you can pass it as a parameter to the [`triangulate()`](https://github.com/snorpey/triangulate-image#triangulate) function.

the `vertexCount` parameter is used in the [`getVerticesFromPoints()`](https://github.com/snorpey/triangulate-image/blob/master/src/polygons/getVerticesFromPoints.js#L13) function.

please let me know if my answer is useful or if you need some more information.

thank you!
