### ISSUE TITLE
great!

### ISSUE THREAD

**Issue by zcdliuwei** [snorpey/triangulate-image#91]
How amazing and interesting your repository code is ！！
Do you have Python version of your algorithm ？

**Comment by snorpey** [comment]
hey @zcdliuwei thank you for your interest in this project. this project is written in javascript and i currently don't have plans to port it to other programming languages.

there are however other projects that do similar things in other programming languages, including python. 
- https://github.com/MauriceGit/Delaunay_Triangulation
- http://www.degeneratestate.org/posts/2017/May/24/images-to-triangles/
